apiVersion: v1
kind: Service
metadata:
  name: token-vending-machine
  namespace: token-vending-machine
spec:
  selector:
    app: token-vending-machine
  ports:
    - port: 80
      targetPort: 8000

